In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objs as go

In [2]:
#Code Implementation Task: Implement code to fill the missing data (impute) in daily_vaccinations column per country with the minimum daily vaccination number of relevant countries.  
#Note: If a country does not have any valid vaccination number yet, fill it with “0” (zero). 

df = pd.read_csv('https://www.piworks.net/Upload/Document/Original/country_vaccination_stats.csv')

df['daily_vaccinations'] = df['daily_vaccinations'].fillna(0)


min_daily_vaccinations_by_country = df.groupby('country')['daily_vaccinations'].min()


df['daily_vaccinations'] = df.apply(lambda x: min_daily_vaccinations_by_country[x['country']] if x['daily_vaccinations'] == 0 else x['daily_vaccinations'], axis=1)

df

,country,date,daily_vaccinations,vaccines
0,Argentina,12/29/2020,0.0,Sputnik V
1,Argentina,12/30/2020,15656.0,Sputnik V
2,Argentina,12/31/2020,15656.0,Sputnik V
3,Argentina,1/1/2021,11070.0,Sputnik V
4,Argentina,1/2/2021,8776.0,Sputnik V
...,...,...,...,...
1497,Wales,1/20/2021,11105.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1498,Wales,1/21/2021,12318.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1499,Wales,1/22/2021,15148.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1500,Wales,1/23/2021,17371.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1501,Wales,1/24/2021,17063.0,"Oxford/AstraZeneca, Pfizer/BioNTech"